# version: "3.7"


services:
  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Web UI
      - "15692:15692" # <== Порт для Prometheus метрик
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_prometheus true"
    networks:
      - monitoring

  # jaeger:
  #   image: jaegertracing/all-in-one:1.49
  #   ports:
  #     - "16686:16686" # Веб-интерфейс Jaeger
  #     - "6831:6831/udp" # Для агентов

  tempo:
    image: grafana/tempo:2.2.2
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200" # Tempo API
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP


  grafana:
    image: grafana/grafana:10.2.3
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - tempo
    networks:
      - monitoring


  prometheus:
      container_name: prometheus
      image: prom/prometheus:v2.48.0
      volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
      ports:
        - "9090:9090"
      networks:
        - monitoring

  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter
    environment:
      RABBIT_USER: admin
      RABBIT_PASSWORD: admin
      RABBIT_URL: http://rabbitmq:15672
    ports:
      - "9419:9419"
    depends_on:
      - rabbitmq

  alertmanager:
    image: prom/alertmanager
    hostname: alertmanager
    container_name: alertmanager


    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge


