global:
  scrape_interval: 5s


scrape_configs:
  - job_name: "fastapi_gateway"
    static_configs:
      - targets: ["gateway:8000", "localhost:8000"]


  - job_name: "fastapi_service"
    static_configs:
      - targets: ["service:8001", "localhost:8001"]

  - job_name: 'rabbitmq'
    static_configs:
        - targets: ['rabbitmq-exporter:9419']

  alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093


  rule_files:
    - "alert.rules.yml"